# Generated by Django 3.1.5 on 2022-01-16 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_post_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auther',
            new_name='author',
        ),
    ]
